# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIDE_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import serial
import numpy 
import matplotlib.pyplot as plt
import numpy.matlib as npm
from copy import copy, deepcopy
from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 645)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 80, 970, 521))
        self.groupBox_2.setObjectName("groupBox_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView.setGeometry(QtCore.QRect(10, 20, 900, 101))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView_2.setGeometry(QtCore.QRect(10, 130, 900, 381))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 970, 81))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(350, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 40, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(590, 10, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(590, 40, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(0, 10, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 980, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.adquirir_datos)
        self.pushButton_2.clicked.connect(self.graficar_giroscopio)
        self.pushButton_3.clicked.connect(self.graficar_acelerometro)
        self.pushButton_4.clicked.connect(self.graficar_magnetometro)

        # Buffer global de datos dentro de la clase para compartir entre botones
        # 13 columnas: índice | timer | cont_timer | ax | ay | az | gx | gy | gz | mx | my | mz | temp
        self.datos_globales = numpy.zeros((100, 13))  # Inicializa la matriz de datos con ceros
        self.datos_capturados = False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GRAFICAS"))
        self.pushButton.setText(_translate("MainWindow", "LEER DATOS"))
        self.pushButton_2.setText(_translate("MainWindow", "GRAFICAR GIROSCOPIO"))
        self.pushButton_3.setText(_translate("MainWindow", "GRAFICAR ACELEROMETRO"))
        self.pushButton_4.setText(_translate("MainWindow", "GRAFICAR MAGNETOMETRO"))
        self.label.setText(_translate("MainWindow", "LECTURA SENSOR MPU 9250"))

    def adquirir_datos(self):
        """Función encargada de iniciar la toma de datos y mostrarla en un monitor serial integrado"""
        print("\n--- Iniciando adquisición desde la interfaz (Modo 300 Muestras) ---")
        try:
            # 1. Configurar el puerto serial con un timeout prudente
            data = serial.Serial('COM3', 9600, timeout=2)
            print("Puerto Serial Conectado con éxito a 9600 baudios:", data)
            
            # Asegurar que la matriz global soporte las 600 filas
            self.datos_globales = numpy.zeros((600, 13))
            
            # 2. Reemplazar dinámicamente el graphicsView por el Monitor de Texto
            self.monitor_serial = QtWidgets.QTextEdit(self.groupBox_2)
            self.monitor_serial.setGeometry(self.graphicsView.geometry()) 
            self.monitor_serial.setReadOnly(True) 
            
            fuente_consola = QtGui.QFont("Courier New", 9)
            self.monitor_serial.setFont(fuente_consola)
            self.monitor_serial.setStyleSheet("background-color: #1e1e1e; color: #ffffff;") 
            self.graphicsView.hide() 
            self.monitor_serial.show() 
            
            cabecera = "Índice\tTimer\tCont\tax\tay\taz\tgx\tgy\tgz\tmx\tmy\tmz\tTemp\n"
            self.monitor_serial.setText(cabecera)
            self.monitor_serial.append("-" * 90 + "\n")
            QtWidgets.QApplication.processEvents()

            print("Enviando comando de disparo H para 300 muestras...")
            data.flushInput() # Limpiar cualquier basura previa del buffer
            data.write(b'H') 
            
            i = 0
            intentos_maximos = 1000  # Evita bucles infinitos si la STM32 deja de transmitir
            intentos = 0
            
            while i < 600 and intentos < intentos_maximos:
                intentos += 1
                rec = data.readline()
                
                if not rec: # Si el puerto no devuelve nada en este ciclo, continúa
                    continue
                    
                rec = rec.decode("utf-8", errors="ignore").strip()
                rec_split = rec.split()
                
                if not rec_split:
                    continue
                
                # Validar rigurosamente que tengamos exactamente las 13 columnas numéricas
                if len(rec_split) == 13 and not any(alpha.isalpha() for alpha in rec_split[0:13]):
                    try:
                        # Guardar en la matriz de 300 elementos
                        self.datos_globales[i][0:13] = [float(val) for val in rec_split]
                        
                        # Mostrar en la terminal visual de la GUI
                        self.monitor_serial.append(rec)
                        self.monitor_serial.moveCursor(QtGui.QTextCursor.End)
                        
                        # PROCESAMIENTO VISUAL: Refresca la UI cada 5 muestras para no saturar a PyQt5
                        if i % 1 == 0:
                            QtWidgets.QApplication.processEvents()
                            
                        i += 1
                    except ValueError:
                        # Si una línea se corrompió en el camino por la velocidad, la ignora de forma segura
                        continue
                        
            print(f"Captura finalizada con éxito. Se procesaron {i} muestras de manera limpia.")
            self.datos_capturados = True
            data.close()
            
        except Exception as e:
            print(f"Error en la adquisición física: {e}")


    def graficar_giroscopio(self):
        if not self.datos_capturados:
            print("Error: Primero debes presionar 'LEER DATOS'.")
            return

        SENSITIVITY_GYRO = 250.0/32768.0
        datos1 = deepcopy(self.datos_globales)

        # SIN CALIBRAR: Multiplicación directa por la sensibilidad en las columnas 6, 7 y 8
        for j in range(0, 300):
            datos1[j][6] = (datos1[j, 6]) * SENSITIVITY_GYRO
            datos1[j][7] = (datos1[j, 7]) * SENSITIVITY_GYRO
            datos1[j][8] = (datos1[j, 8]) * SENSITIVITY_GYRO

        # Crear figura interna de Matplotlib adaptada al ancho de graphicsView_2
        fig = plt.figure(figsize=(8.5, 3.8), dpi=100)
        ax = fig.subplots(2, 2)
        fig.suptitle('Giroscopio no calibrado MPU9250', fontsize=10, fontweight='bold')
        
        # Mapeo de ejes X (columna 2 - Tiempo) e Y (columnas 6, 7 y 8 - Giroscopio)
        ax[0,0].plot(datos1[:, 2], datos1[:, 6], 'r')
        ax[0,0].set_title('gx', fontsize=8)
        ax[0,0].grid(True, linestyle='--', alpha=0.5)
        
        ax[0,1].plot(datos1[:, 2], datos1[:, 7], 'g')
        ax[0,1].set_title('gy', fontsize=8)
        ax[0,1].grid(True, linestyle='--', alpha=0.5)
        
        ax[1,0].plot(datos1[:, 2], datos1[:, 8], 'b')
        ax[1,0].set_title('gz', fontsize=8)
        ax[1,0].grid(True, linestyle='--', alpha=0.5)
        
        ax[1,1].plot(datos1[:, 2], datos1[:, 6], 'r', label='gx')
        ax[1,1].plot(datos1[:, 2], datos1[:, 7], 'g', label='gy')
        ax[1,1].plot(datos1[:, 2], datos1[:, 8], 'b', label='gz')
        ax[1,1].set_title('gx, gy y gz', fontsize=8)
        ax[1,1].grid(True, linestyle='--', alpha=0.5)
        
        fig.tight_layout()

        # Renderizar e incrustar la cuadrícula dentro de graphicsView_2
        canvas = FigureCanvas(fig)
        scene = QtWidgets.QGraphicsScene()
        scene.addWidget(canvas)
        self.graphicsView_2.setScene(scene)

    def graficar_acelerometro(self):
        if not self.datos_capturados:
            print("Error: Primero debes presionar 'LEER DATOS'.")
            return

        SENSITIVITY_ACCEL = 2.0/32768.0
        datos2 = deepcopy(self.datos_globales)

        # SIN CALIBRAR: Se eliminó la resta de la lista 'offsets'
        for j in range(0, 300):
            datos2[j][3] = (datos2[j, 3]) * SENSITIVITY_ACCEL
            datos2[j][4] = (datos2[j, 4]) * SENSITIVITY_ACCEL
            datos2[j][5] = (datos2[j, 5]) * SENSITIVITY_ACCEL

        # Crear figura interna de Matplotlib adaptada al ancho de graphicsView_4
        fig = plt.figure(figsize=(8.5, 3.8), dpi=100)
        ax = fig.subplots(2, 2)
        fig.suptitle('Acelerómetro no calibrado MPU9250', fontsize=10, fontweight='bold')
        
        # Mapeo de ejes X (columna 2 - Tiempo) e Y (columnas 3, 4 y 5 - Acelerómetro)
        ax[0,0].plot(datos2[:, 2], datos2[:, 3], 'r')
        ax[0,0].set_title('ax', fontsize=8)
        ax[0,0].grid(True, linestyle='--', alpha=0.5)
        
        ax[0,1].plot(datos2[:, 2], datos2[:, 4], 'g')
        ax[0,1].set_title('ay', fontsize=8)
        ax[0,1].grid(True, linestyle='--', alpha=0.5)
        
        ax[1,0].plot(datos2[:, 2], datos2[:, 5], 'b')
        ax[1,0].set_title('az', fontsize=8)
        ax[1,0].grid(True, linestyle='--', alpha=0.5)
        
        ax[1,1].plot(datos2[:, 2], datos2[:, 3], 'r', label='ax')
        ax[1,1].plot(datos2[:, 2], datos2[:, 4], 'g', label='ay')
        ax[1,1].plot(datos2[:, 2], datos2[:, 5], 'b', label='az')
        ax[1,1].set_title('ax, ay y az', fontsize=8)
        ax[1,1].grid(True, linestyle='--', alpha=0.5)
        
        fig.tight_layout()

        # Renderizar e incrustar la cuadrícula dentro de graphicsView_4
        # (Asegúrate de que graphicsView_4 sea el asignado en tu layout para el acelerómetro)
        canvas = FigureCanvas(fig)
        scene = QtWidgets.QGraphicsScene()
        scene.addWidget(canvas)
        self.graphicsView_4.setScene(scene)

    def graficar_magnetometro(self):
        if not self.datos_capturados:
            print("Error: Primero debes presionar 'LEER DATOS'.")
            return

        try:
            # 1. Escalamiento de datos RAW del AK8963
            SENSITIVITY_MAG = 0.15
            datos3 = deepcopy(self.datos_globales)

            # EXTRAEMOS LOS DATOS COMPLETAMENTE CRUDOS (SIN RESTAR OFFSETS)
            # Para que coincida con las unidades del PDF (mG - miliGauss), 
            # multiplicamos por la sensibilidad adecuada.
            mx = datos3[:, 10] * SENSITIVITY_MAG
            my = datos3[:, 11] * SENSITIVITY_MAG
            mz = datos3[:, 12] * SENSITIVITY_MAG

            # 2. Crear una figura de UN SOLO SUBPLOT grande (como en tu PDF)
            fig = plt.figure(figsize=(7, 5), dpi=100)
            ax = fig.add_subplot(1, 1, 1)
            
            # --- MAPEADO EXACTO DE EJES PARA SEPARAR LAS ELIPSES (Como en la guía) ---
            # Elipse Azul (MYZ): Eje X = my, Eje Y = mz
            ax.scatter(my, mz, c='b', marker='.', s=10, label='MYZ')
            
            # Elipse Roja (MXZ): Eje X = mx, Eje Y = mz
            ax.scatter(mx, mz, c='r', marker='.', s=10, label='MXZ')
            
            # Elipse Verde (MXY): Eje X = mx, Eje Y = my
            ax.scatter(mx, my, c='g', marker='.', s=10, label='MXY')
            
            # Títulos y etiquetas idénticos al formato de la guía
            ax.set_title('Magnetometro no calibrado MPU9250', fontsize=10, fontweight='bold')
            ax.set_xlabel('Magnetic Field [mG]', fontsize=9)
            ax.set_ylabel('Magnetic Field [mG]', fontsize=9)
            
            # Activar cuadrícula y leyenda
            ax.grid(True, linestyle='--', alpha=0.6)
            ax.legend(fontsize=8, loc='upper right')
            
            fig.tight_layout()

            # 3. Renderizar e incrustar la gráfica limpia dentro de graphicsView_3
            canvas = FigureCanvas(fig)
            scene = QtWidgets.QGraphicsScene()
            scene.addWidget(canvas)
            self.graphicsView_2.setScene(scene)
            
        except Exception as e:
            print(f"Error al generar la gráfica sin calibrar: {e}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
